spring.application.name=polarisdigitech
# Enable console, fix URL, and set persistent DB name
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.generate-unique-name=false
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=

# Run schema.sql automatically
spring.sql.init.mode=always

# Configurable maximum box capacity
# Environment variable overrides the default.
box.max-weight=${BOX_MAX_WEIGHT:500}

server.port=8080