CREATE TABLE boxes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    txref VARCHAR(20) NOT NULL UNIQUE,

    current_weight INT NOT NULL DEFAULT 0,

    battery_percentage INT NOT NULL,

    state VARCHAR(20) NOT NULL
);

CREATE TABLE items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name VARCHAR(255) NOT NULL,

    weight INT NOT NULL,

    code VARCHAR(255) NOT NULL,

    box_id BIGINT NOT NULL,

    CONSTRAINT fk_box_item
        FOREIGN KEY (box_id)
        REFERENCES boxes(id)
);